//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionnaireMSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Answerer { get; set; }
        public int Question { get; set; }
        public System.DateTime Date { get; set; }
        public string Variant { get; set; }
    
        public virtual Question Question1 { get; set; }
        public virtual User User { get; set; }
    }
}
